fig_tree/apps/authentication/urls.py
"""
The `urls` module maps URL endpoints to django views defined in the parent
application. For root level URL routing, see the project level `urls` module.
View objects can be found in the `views` module.

# URL Routing Configuration

| URL Pattern                | View Class                  | Registered Name           |
|----------------------------|-----------------------------|---------------------------|
| `login/`                   | `LoginView`                 | `login`                   |
| `logout/`                  | `LogoutView`                | `logout`                  |
| `password_reset/`          | `PasswordResetView`         | `password-reset`          |
| `password_reset/done/`     | `PasswordResetDoneView`     | `password-reset-done`     |
| `'reset/<uidb64>/<token>/` | `PasswordResetConfirmView`  | `password-reset-confirm`  |
| `reset/done/`              | `PasswordResetCompleteView` | `password-reset-complete` |
"""

from django.urls import path

from .views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

fig_tree/apps/signup/urls.py
"""
The `urls` module maps URL endpoints to django views defined in the parent
application. For root level URL routing, see the project level `urls` module.
View objects can be found in the `views` module.

# URL Routing Configuration

| URL                      | View                   | Name              |
|--------------------------|------------------------|-------------------|
| `/`                      | `SignUpView`           | `new-user`        |
| `sent/`                  | `ActivationSentView`   | `activation-sent` |
| `[AUTHENTICATION-TOKEN]` | `ActivateAccountView`  | `activate`        |
"""

from django.urls import path, re_path

from .views import *

app_name = 'signup'

token_regex = r'(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,50})'

urlpatterns = [
    path('', SignUpView.as_view(), name='new-user'),
    path('sent', ActivationSentView.as_view(), name='activation-sent'),
    re_path(token_regex, ActivateAccountView.as_view(), name='activate'),
]

fig_tree/main/urls.py
"""
The `main.urls` module defines the primary website URL configuration.
The table below outlines routing patterns different URL endpoints.
Further traffic routing is handled internally by each application to
route specific URLs to individual pages.

| URL Pattern | Application                | Namespace      |
|-------------|----------------------------|----------------|
| `admin/`    | `apps.admin`               | `admin`        |
| `auth/`     | `apps.authentication`      | `auth`         |
| `gen_data/` | `apps.gen_data`            | `gen_data`     |
| `signup/`   | `apps.signup`              | `signup`       |

The following pages are included to support testing and development.

| URL Pattern | Description                    | Registered Name |
|-------------|--------------------------------|-----------------|
| `tests/400` | Renders a 400 HTTP error code. | `test-400`      |
| `tests/403` | Renders a 403 HTTP error code. | `test-403`      |
| `tests/404` | Renders a 404 HTTP error code. | `test-404`      |
| `tests/500` | Renders a 500 HTTP error code. | `test-500`      |
"""

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from apps.error_pages import handlers

# Enable custom error code handling
# See the `error_pages` app for more information
handler400 = handlers.handler400
handler403 = handlers.handler403
handler404 = handlers.handler404
handler500 = handlers.handler500

urlpatterns = [
    path('', TemplateView.as_view(template_name='pages/index.html'), name='home'),

    # Add urls from plugins and applications
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),
    path('gen_data/', include('apps.gen_data.urls', namespace='gen_data')),
    path('signup/', include('apps.signup.urls', namespace='signup')),

    # Add dedicated error pages for testing purposes
    path('err/400', handler400, name='test-400'),
    path('err/403', handler403, name='test-403'),
    path('err/404', handler404, name='test-404'),
    path('err/500', handler500, name='test-500'),
]

fig_tree/apps/signup/models.py
"""
The `models` module uses data classes to define and interact with the
application database schema. Each model class reflects the schema for a
distinct database table and provides a high-level API to query and interact
with table data.
"""

import django.contrib.auth.models
from django.contrib import auth
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import *

__all__ = ['AuthUser']


class AuthUser(auth.models.AbstractBaseUser, auth.models.PermissionsMixin):
    """Custom model for user account data"""

    class Meta:
        verbose_name = 'User'

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email', ]

    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_super_user = models.BooleanField(default=False)

    objects = AuthUserManager()

fig_tree/apps/signup/forms.py
"""
The `forms` module defines form classes used to define the structure, input
fields, and validation rules for various data input forms. Server and client
side form validation is handled by application views found in the `views`
module.
"""

from django.contrib.auth import forms
from django.forms import fields as form_fields

from .models import *

__all__ = ['UserCreationForm', 'UserChangeForm']

EXISTING_USERNAME_ERROR = "An account with this username already exists."
EXISTING_EMAIL_ERROR = "An account with this email address already exists."


class UserCreationForm(forms.UserCreationForm):
    """Form for creating a new user account"""

    class Meta(forms.UserCreationForm.Meta):
        model = AuthUser
        fields = ('username', 'email')
        field_classes = {
            'username': forms.UsernameField,
            'email': form_fields.EmailField
        }
        error_messages = {
            "username": {"unique": EXISTING_USERNAME_ERROR},
            "email": {"unique": EXISTING_EMAIL_ERROR},
        }


class UserChangeForm(forms.UserChangeForm):
    """Form for modifying existing user data"""

    class Meta:
        model = AuthUser
        fields = ('username', 'email')
        field_classes = {
            'username': forms.UsernameField,
            'email': form_fields.EmailField
        }
        error_messages = {
            "username": {"unique": EXISTING_USERNAME_ERROR},
            "email": {"unique": EXISTING_EMAIL_ERROR},
        }

fig_tree/apps/signup/views.py
"""
The `views` module defines classes for rendering templates based on incoming
HTTP requests. View classes are responsible for processing form/request data,
interacting with database models/serializers, managing application business
logic, and returning rendered HTTP responses.

Whenever possible, generic base classes are used to implement common behavior
for HTTP request handling.
"""

from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.sites.models import Site
from django.core.mail import EmailMessage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import CreateView, TemplateView, View

from .forms import UserCreationForm
from .models import AuthUser

__all__ = ['SignUpView', 'ActivationSentView', 'ActivateAccountView']

activation_token_generator = PasswordResetTokenGenerator()


class SignUpView(CreateView):
    """View for handling new user creation requests"""

    form_class = UserCreationForm
    template_name = 'pages/signup/create_new_user.html'
    success_url = reverse_lazy('signup:activation-sent')

    def form_valid(self, form: UserCreationForm) -> bool:
        """Creates a new user account and sends an email confirming user contact information

        This method is automatically called on POST requests after successfully
        validating data submitted in the `form_class` form.

        Args:
            form: The form to validate

        Return:
            Whether the form is valid
        """

        user = form.save(commit=False)
        user.save()

        current_site = Site.objects.get_current()

        email_subject = 'New account activation'
        message = render_to_string('pages/signup/activate_account_email.html', {
            'user': user,
            'domain': current_site.domain,
            'protocol': 'https',
            'uid': urlsafe_base64_encode(force_bytes(user.id)),
            'token': activation_token_generator.make_token(user)
        })

        email_address = form.cleaned_data.get('email')
        EmailMessage(email_subject, message, to=[email_address]).send()

        # The parent `form_valid` method redirects requests to `self.success_url`
        return super().form_valid(form)


class ActivationSentView(TemplateView):
    """View for telling user's to check their email for a confirmation notice"""

    template_name = "pages/signup/activation_sent.html"


class ActivateAccountView(View):
    """View for marking accounts as active and finalizing account creation"""

    def get(self, request: HttpRequest, uidb64: str, token: str) -> HttpResponse:
        """Handle an incoming HTTP request

        Args:
            request: Incoming HTTP request
            uidb64: Base 64 encoded user id
            token: Account authentication token

        Return:
            The outgoing HTTPResponse
        """

        try:
            uid = force_bytes(urlsafe_base64_decode(uidb64))
            user = AuthUser.objects.get(id=uid)

        # Catch all errors but explicitly list the expected ones
        except(TypeError, ValueError, OverflowError, AuthUser.DoesNotExist, Exception):
            user = None

        if user is not None and activation_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return render(request, 'pages/signup/activation_success.html')

        return render(request, 'pages/signup/invalid_activation_link.html')

fig_tree/templates/pages/signup/activate_account_email.html
{% load i18n %}
{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "To activate your account, please visit the following link:" %}

{{ protocol }}://{{ domain }}{% url 'signup:activate' uidb64=uid token=token %}

Yours,
The {{ site_name }} Team
{% endautoescape %}

fig_tree/templates/pages/signup/activation_sent.html
{% extends 'layouts/center_card.html' %}

{% block title %}Welcome!{% endblock %}

{% block card_header_content %}
  <h3>Welcome!</h3>
{% endblock %}

{% block card_body_content %}
  <p>An email has been sent to the email address you provided with instructions for validating your account.</p>
  <p>Please check your inbox and follow the instructions to finish the account creation process.</p>
{% endblock %}

fig_tree/templates/pages/signup/activation_success.html
{% extends 'layouts/center_card.html' %}

{% block title %}Validation Successful{% endblock %}

{% block card_header_content %}
  <h3>Account Created</h3>
{% endblock %}

{% block card_body_content %}
  <p>Thank you for validating your account. Please <a id="id_login" href="{% url 'auth:login' %}">log in</a> to continue.</p>
{% endblock %}

fig_tree/templates/pages/signup/create_new_user.html
{% extends 'layouts/base.html' %}
{% load static widget_tweaks %}

{% block title %}Sign Up{% endblock %}
{% block header %}{% endblock %}

{% block main_content %}

  <section>
    <div class="container">
      <div class="px-4 py-5 px-md-5 text-center text-lg-start">
        <div class="row gx-lg-5 align-items-center">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <h1 class="my-5 display-3 fw-bold ls-tight">
              Take your story<br />
              <span class="text-primary">to the next level</span>
            </h1>
            <p class="text-gray">
              Sign up now to see why we're so much more than a best in class data management platform.
              Effortlessly organize your family history and build a shareable digital legacy that spans generations.
            </p>
          </div>

          <div class="col-lg-6 mb-5 mb-lg-0">
            <div class="card">
              <div class="card-header">
                <h2 class="h3">Create a New Account</h2>
              </div>

              <div class="card-body py-4 px-md-5">
                <form method="post" action="{% url 'signup:new-user' %}">
                  {% csrf_token %}

                  <div class="mb-3">
                    <label for="id_username" class="form-label">Username</label>
                    {% render_field form.username class="form-control" placeholder="username" %}
                    {% if form.username.errors %}
                      <p id="id_username_error" class="text-danger pt-1">
                        {{ form.username.errors.0|escape }}
                      </p>
                    {% endif %}
                  </div>

                  <div class="mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    {% render_field form.email class="form-control" placeholder="name@domain.com" %}
                    {% if form.email.errors %}
                      <p id="id_email_error" class="text-danger pt-1">
                        {{ form.email.errors.0|escape }}
                      </p>
                    {% endif %}
                  </div>

                  <div class="mb-3">
                    <label for="id_password1" class="form-label">Password</label>
                    {% render_field form.password1 class="form-control" placeholder="password" %}
                  </div>

                  <div class="mb-4">
                    <label for="i3_password2" class="form-label">Confirm Password</label>
                    {% render_field form.password2 class="form-control" placeholder="password" %}
                    {% if form.password2.errors %}
                      <p id="id_password_error" class="text-danger pt-1">
                        {{ form.password2.errors.0|escape }}
                      </p>
                    {% endif %}
                  </div>

                  <button id="id_submit" type="submit" class="btn btn-primary w-100">Sign Up</button>
                  <hr class="my-4">
                  <div class="text-center text-muted">
                    <p>Already have an account? <a href="{% url 'auth:login' %}">Click here to login</a></p>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

fig_tree/templates/pages/signup/invalid_activation_link.html
{% extends 'layouts/center_card.html' %}

{% block title %}Invalid Link{% endblock %}

{% block card_header_content %}
  <h3>Invalid Activation Link</h3>
{% endblock %}

{% block card_body_content %}
  <p>The activation link you have used is no longer valid.</p>
  <a class="btn btn-primary w-100 my-2" id="id_home" href="{% url 'home' %}" type="submit">Go Home</a>
{% endblock %}