fig_tree/apps/authentication/urls.py
"""
The `urls` module maps URL endpoints to django views defined in the parent
application. For root level URL routing, see the project level `urls` module.
View objects can be found in the `views` module.

# URL Routing Configuration

| URL Pattern                | View Class                  | Registered Name           |
|----------------------------|-----------------------------|---------------------------|
| `login/`                   | `LoginView`                 | `login`                   |
| `logout/`                  | `LogoutView`                | `logout`                  |
| `password_reset/`          | `PasswordResetView`         | `password-reset`          |
| `password_reset/done/`     | `PasswordResetDoneView`     | `password-reset-done`     |
| `'reset/<uidb64>/<token>/` | `PasswordResetConfirmView`  | `password-reset-confirm`  |
| `reset/done/`              | `PasswordResetCompleteView` | `password-reset-complete` |
"""

from django.urls import path

from .views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

fig_tree/apps/signup/urls.py
"""
The `urls` module maps URL endpoints to django views defined in the parent
application. For root level URL routing, see the project level `urls` module.
View objects can be found in the `views` module.

# URL Routing Configuration

| URL                      | View                   | Name              |
|--------------------------|------------------------|-------------------|
| `/`                      | `SignUpView`           | `new-user`        |
| `sent/`                  | `ActivationSentView`   | `activation-sent` |
| `[AUTHENTICATION-TOKEN]` | `ActivateAccountView`  | `activate`        |
"""

from django.urls import path, re_path

from .views import *

app_name = 'signup'

token_regex = r'(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,50})'

urlpatterns = [
    path('', SignUpView.as_view(), name='new-user'),
    path('sent', ActivationSentView.as_view(), name='activation-sent'),
    re_path(token_regex, ActivateAccountView.as_view(), name='activate'),
]

fig_tree/main/urls.py
"""
The `main.urls` module defines the primary website URL configuration.
The table below outlines routing patterns different URL endpoints.
Further traffic routing is handled internally by each application to
route specific URLs to individual pages.

| URL Pattern | Application                | Namespace      |
|-------------|----------------------------|----------------|
| `admin/`    | `apps.admin`               | `admin`        |
| `auth/`     | `apps.authentication`      | `auth`         |
| `gen_data/` | `apps.gen_data`            | `gen_data`     |
| `signup/`   | `apps.signup`              | `signup`       |

The following pages are included to support testing and development.

| URL Pattern | Description                    | Registered Name |
|-------------|--------------------------------|-----------------|
| `tests/400` | Renders a 400 HTTP error code. | `test-400`      |
| `tests/403` | Renders a 403 HTTP error code. | `test-403`      |
| `tests/404` | Renders a 404 HTTP error code. | `test-404`      |
| `tests/500` | Renders a 500 HTTP error code. | `test-500`      |
"""

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from apps.error_pages import handlers

# Enable custom error code handling
# See the `error_pages` app for more information
handler400 = handlers.handler400
handler403 = handlers.handler403
handler404 = handlers.handler404
handler500 = handlers.handler500

urlpatterns = [
    path('', TemplateView.as_view(template_name='pages/index.html'), name='home'),

    # Add urls from plugins and applications
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),
    path('gen_data/', include('apps.gen_data.urls', namespace='gen_data')),
    path('signup/', include('apps.signup.urls', namespace='signup')),

    # Add dedicated error pages for testing purposes
    path('err/400', handler400, name='test-400'),
    path('err/403', handler403, name='test-403'),
    path('err/404', handler404, name='test-404'),
    path('err/500', handler500, name='test-500'),
]

fig_tree/apps/signup/models.py
"""
The `models` module uses data classes to define and interact with the
application database schema. Each model class reflects the schema for a
distinct database table and provides a high-level API to query and interact
with table data.
"""

import django.contrib.auth.models
from django.contrib import auth
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import *

__all__ = ['AuthUser']


class AuthUser(auth.models.AbstractBaseUser, auth.models.PermissionsMixin):
    """Custom model for user account data"""

    class Meta:
        verbose_name = 'User'

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email', ]

    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_super_user = models.BooleanField(default=False)

    objects = AuthUserManager()

fig_tree/apps/authentication/forms.py
"""
The `forms` module defines form classes used to define the structure, input
fields, and validation rules for various data input forms. Server and client
side form validation is handled by application views found in the `views`
module.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm as AuthForm

__all__ = ['AuthenticationForm']


class AuthenticationForm(AuthForm):
    """Extends the built-in form for authenticating users"""

    remember_me = forms.BooleanField(required=False)

fig_tree/apps/authentication/views.py
"""
The `views` module defines classes for rendering templates based on incoming
HTTP requests. View classes are responsible for processing form/request data,
interacting with database models/serializers, managing application business
logic, and returning rendered HTTP responses.

Whenever possible, generic base classes are used to implement common behavior
for HTTP request handling.
"""

from datetime import timedelta

from django.conf import settings
from django.contrib.auth import login, views
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from .forms import *

DEFAULT_REMEMBER_ME_DURATION = timedelta(days=7)

__all__ = [
    'LoginView',
    'LogoutView',
    'PasswordResetView',
    'PasswordResetDoneView',
    'PasswordResetConfirmView',
    'PasswordResetCompleteView',
]


class LoginView(views.LoginView):
    """View for handling existing user authentication"""

    template_name = 'pages/auth/login.html'
    authentication_form = AuthenticationForm
    redirect_authenticated_user = True

    def form_valid(self, form):
        """Security check complete. Log the user in."""

        login(self.request, form.get_user())
        if form.cleaned_data['remember_me']:
            duration = getattr(settings, 'REMEMBER_ME_DURATION', DEFAULT_REMEMBER_ME_DURATION)
            self.request.session.set_expiry(duration)

        else:
            self.request.session.set_expiry(0)

        return HttpResponseRedirect(self.get_success_url())


class LogoutView(views.LogoutView):
    """View for logging out users"""

    template_name = 'pages/auth/logged_out.html'


class PasswordResetView(views.PasswordResetView):
    """View for requesting a reset password link via email"""

    template_name = 'pages/auth/password_reset_form.html'
    email_template_name = 'authentication/password_reset_email.html'
    success_url = reverse_lazy('auth:password-reset-done')


class PasswordResetDoneView(views.PasswordResetDoneView):
    """View for confirming that a reset password link has been sent via email"""

    template_name = 'pages/auth/password_reset_done.html'


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    """View for resetting an existing user's password"""

    template_name = 'pages/auth/password_reset_confirm.html'
    success_url = reverse_lazy('auth:password-reset-complete')


class PasswordResetCompleteView(views.PasswordResetCompleteView):
    """View for confirming a user's password has been reset"""

    template_name = 'pages/auth/password_reset_complete.html'

fig_tree/templates/authentication/logged_out.html
{% extends "base/center_card.html" %}

{% block title %}Logout Successful{% endblock %}

{% block additional_css %}
  <meta http-equiv="refresh" content="3;{% url 'home' %}"/>
{% endblock %}

{% block card_header_content %}
  <h3>Success</h3>
{% endblock %}

{% block card_body_content %}
  <p>
    You have been logged out from your account.
    You will be automatically redirected to the <a href="{% url 'home' %}">Home Page</a>.
  </p>
{% endblock %}

fig_tree/templates/authentication/login.html
{% extends "base/center_card.html" %}
{% load static widget_tweaks %}

{% block title %}Login{% endblock %}

{% block card_header_content %}
  <h3>Login</h3>
{% endblock %}

{% block card_body_content %}
  {% if form.errors %}
    <div id="id_login_error" class="alert alert-danger">
      Incorrect username or password.
    </div>
  {% endif %}

  <form method="post" action="{% url 'auth:login' %}">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_username" class="form-label">Username</label>
      {% render_field form.username class="form-control" %}
    </div>
    <div class="mb-4">
      <label for="id_password" class="form-label">Password</label>
      {% render_field form.password class="form-control" %}
    </div>
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        {% render_field form.remember_me type="checkbox" class="form-check-input" %}
        <label class="form-check-label mx-1" for="id_remember_me">Remember me</label>
      </div>
      <div class="col">
        <a id="id_forgot_password" href="{% url 'auth:password-reset' %}">Forgot your password?</a>
      </div>
    </div>
    <button id="id_submit" type="submit" class="btn btn-primary w-100 mb-2">Log In</button>
    <hr class="mb-3">
    <div class="text-center text-muted">
      Don't have account yet? <a id="id_signup" href="{% url 'signup:new-user' %}">Sign up</a>
    </div>
  </form>
{% endblock %}

fig_tree/templates/authentication/password_reset_complete.html
{% extends "base/center_card.html" %}
{% load static %}

{% block title %}Reset Password{% endblock %}

{% block card_header %}{% endblock %}

{% block card_body_content %}
  <div class="text-center">
    <p>Your password has been reset successfully.</p>
    <div class="form-group">
      <a id="id_login" href="{% url 'auth:login' %}" type="submit" class="btn btn-primary mx-1">Sign In</a>
      <a id="id_home" href="{% url 'home' %}" type="submit" class="btn btn-secondary mx-1">Go Home</a>
    </div>
  </div>
{% endblock %}

fig_tree/templates/authentication/password_reset_confirm.html
{% extends "base/center_card.html" %}
{% load static widget_tweaks %}

{% block title %}Reset Password{% endblock %}

{% block card_header_content %}
  {% if validlink %}
    <h3>Password Reset</h3>
  {% else %}
    <h3>Invalid Reset Link</h3>
  {% endif %}
{% endblock %}

{% block card_body_content %}
  {% if validlink %}

    <p>Please choose your new password.</p>
    <form method="post" novalidate>
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_new_password1" class="form-label">Password</label>
        {% render_field form.new_password1 class="form-control m2-4" placeholder="password" %}
      </div>

      <div class="mb-3">
        <label for="id_new_password2" class="form-label">Confirm Password</label>
        {% render_field form.new_password2 class="form-control" placeholder="password" %}
        {% if form.new_password2.errors %}
          <p id="id_password_error" class="text-danger pt-1">
            {{ form.new_password2.errors.0|escape }}
          </p>
        {% endif %}
      </div>

      <button id="id_submit_btn" type="submit" class="btn btn-primary w-100 my-2">Save</button>
    </form>

  {% else %}

    <p>
      The link you have used is either expired or no longer valid.
      <a id="id_try_again" href="{% url 'auth:password-reset' %}">Request new reset link</a>.
    </p>

  {% endif %}
{% endblock %}

fig_tree/templates/authentication/password_reset_done.html
{% extends "base/center_card.html" %}

{% block title %}Reset Password{% endblock %}

{% block card_header_content %}
  <h3>Reset Email Sent</h3>
{% endblock %}

{% block card_body_content %}
  <p>An email has been sent with instructions for resetting your password.</p>
  <p>If you don't receive an email shortly, please check your spam folder and make sure you entered the correct address.</p>
{% endblock %}

fig_tree/templates/authentication/password_reset_form.html
{% extends "base/center_card.html" %}
{% load static widget_tweaks %}

{% block title %}Reset Password{% endblock %}

{% block card_header_content %}
  <h3>Reset Your Password</h3>
{% endblock %}

{% block card_body_content %}
  <p class="mb-4">Please enter the email address associated with your account. An email will be sent with instructions for resetting your password.</p>

  <form method="post" novalidate>
    {% csrf_token %}
    <div class="mb-4">
      <label for="id_email" class="form-label">Email</label>
      {% render_field form.email class="form-control" placeholder="name@domain.com" %}
      {% if form.email.errors %}
        <p id="id_email_error" class="text-danger pt-1">
          {{ form.email.errors.0|escape }}
        </p>
      {% endif %}
    </div>
    <button id="id_submit" type="submit" class="btn btn-primary w-100">Request A New Password</button>
  </form>
{% endblock %}